export const SymbolEnum = {
  USDT: 'USDT',
  BUSD: 'BUSD',
  BRL: 'BRL',
  EUR: 'EUR',
  BTC: 'BTC',
  ETH: 'ETH',
  LTC: 'LTC',
  XMR: 'XMR',
  XRP: 'XRP',
  ADA: 'ADA',
  BNB: 'BNB',
  BCH: 'BCH',
  DOT: 'DOT',
  ENJ: 'ENJ',
  CHZ: 'CHZ',
  AXS: 'AXS',
  SOL: 'SOL',
  CAKE: 'CAKE',
  LUNA: 'LUNA',
  LINK: 'LINK',
  DOGE: 'DOGE',
  AAVE: 'AAVE',
  ALICE: 'ALICE',
} as const

export type SymbolEnumKeys = keyof typeof SymbolEnum